"""Training-fit checks, annotation smells, and dataset merging."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import numpy as np
import pytest
import yaml
from PIL import Image

from conftest import write_sample
from dsdoctor import merge
from dsdoctor.dataset import Dataset
from dsdoctor.detectors import run


# ------------------------------------------------------- training fit

def test_undetectable_boxes_depend_on_imgsz(clean_root):
    """The same dataset is fine at one resolution and lossy at another."""
    p = clean_root / "labels" / "train" / "t000.txt"
    # 0.01 normalised = 6.4px at 640 (fine), 4.2px at 416 (below stride 8)
    p.write_text("0 0.5 0.5 0.010 0.010\n")

    ds = Dataset(clean_root)
    ds.imgsz = 1280
    assert run("training_fit_scan", ds) == []

    ds = Dataset(clean_root)
    ds.imgsz = 320
    found = [f for f in run("training_fit_scan", ds)
             if f.type == "undetectable_at_imgsz"]
    assert len(found) == 1
    assert "train/t000" in found[0].items


def test_training_fit_defaults_to_640(clean_root):
    p = clean_root / "labels" / "train" / "t000.txt"
    p.write_text("0 0.5 0.5 0.001 0.001\n")      # 0.64px at 640: hopeless
    found = run("training_fit_scan", Dataset(clean_root))
    assert any(f.type == "undetectable_at_imgsz" for f in found)
    assert "imgsz=640" in found[0].title


def test_training_fit_ignores_degenerate_boxes(clean_root):
    """geometry_scan owns those; reporting them twice is noise."""
    p = clean_root / "labels" / "train" / "t000.txt"
    p.write_text("0 0.5 0.5 0.0 0.0\n")
    assert run("training_fit_scan", Dataset(clean_root)) == []


def test_over_max_detections(clean_root):
    p = clean_root / "labels" / "train" / "t000.txt"
    p.write_text("\n".join("0 0.5 0.5 0.2 0.2" for _ in range(12)) + "\n")
    ds = Dataset(clean_root)
    ds.max_det = 10
    found = [f for f in run("training_fit_scan", ds)
             if f.type == "over_max_detections"]
    assert len(found) == 1
    assert found[0].items == ["train/t000"]


def test_training_fit_is_silent_on_a_healthy_dataset(clean_root):
    assert run("training_fit_scan", Dataset(clean_root)) == []


# --------------------------------------------------- annotation smells

@pytest.fixture
def varied_root(tmp_path):
    """A dataset whose boxes differ between images, as real ones do.

    `clean_root` is generated by a loop that writes the same coordinates into
    every file, which is a literal instance of the pattern `template_annotation`
    exists to find - so it is the wrong fixture for testing that this check is
    quiet. On the real 600-image corpus the check returns nothing at all; this
    reproduces that property at unit-test size by jittering each box.
    """
    root = tmp_path / "varied"
    rng = np.random.default_rng(7)
    for i in range(20):
        rows = [f"{c} {rng.uniform(0.2, 0.8):.6f} {rng.uniform(0.2, 0.8):.6f} "
                f"{rng.uniform(0.05, 0.2):.6f} {rng.uniform(0.05, 0.2):.6f}"
                for c in range(3)]
        write_sample(root, "train", f"t{i:03d}", rows, seed=i)
    (root / "data.yaml").write_text(yaml.safe_dump(
        {"names": ["person", "car", "cup"], "nc": 3}))
    return root


def test_provenance_is_silent_on_varied_annotations(varied_root):
    assert run("provenance_scan", Dataset(varied_root)) == []


def test_template_annotation_catches_a_script_written_dataset(clean_root):
    """`clean_root` is generated by writing identical rows to every image.

    That is exactly the guilty pattern - a tool, not a photographer, decided
    where these boxes go - so the detector firing here is correct behaviour and
    worth pinning rather than working around.
    """
    found = [f for f in run("provenance_scan", Dataset(clean_root))
             if f.type == "template_annotation"]
    assert len(found) == 1


def test_template_annotation_needs_many_images(varied_root):
    """Four repeats is a coincidence; the threshold is deliberately high."""
    for i in range(4):
        p = varied_root / "labels" / "train" / f"t{i:03d}.txt"
        p.write_text("0 0.123456 0.654321 0.1 0.1\n")
    assert not [f for f in run("provenance_scan", Dataset(varied_root))
                if f.type == "template_annotation"]

    for i in range(4, 9):
        p = varied_root / "labels" / "train" / f"t{i:03d}.txt"
        p.write_text("0 0.123456 0.654321 0.1 0.1\n")
    found = [f for f in run("provenance_scan", Dataset(varied_root))
             if f.type == "template_annotation"]
    assert len(found) == 1
    assert "9 different images" in " ".join(found[0].evidence)


def test_whole_frame_reports_a_pattern_not_a_box(varied_root):
    """One close-up is not a finding; a placeholder pipeline is."""
    p = varied_root / "labels" / "train" / "t000.txt"
    p.write_text(p.read_text() + "0 0.5 0.5 1.0 1.0\n")
    assert not [f for f in run("provenance_scan", Dataset(varied_root))
                if f.type == "whole_frame_box"]

    for i in range(14):
        q = varied_root / "labels" / "train" / f"t{i:03d}.txt"
        q.write_text("0 0.5 0.5 1.0 1.0\n")
    found = [f for f in run("provenance_scan", Dataset(varied_root))
             if f.type == "whole_frame_box"]
    assert len(found) == 1


# ------------------------------------------------------------- merge

def _collection(root: Path, names: list[str], n: int, seed0: int) -> Path:
    for i in range(n):
        write_sample(root, "train", f"img{i}", [f"{i % len(names)} 0.5 0.5 0.2 0.2"],
                     seed=seed0 + i)
    (root / "data.yaml").write_text(yaml.safe_dump({"names": names,
                                                    "nc": len(names)}))
    return root


@pytest.fixture
def collections(tmp_path):
    a = _collection(tmp_path / "a", ["person", "car"], 6, 0)
    b = _collection(tmp_path / "b", ["forklift", "Cars"], 6, 100)
    c = _collection(tmp_path / "c", ["person", "pallet"], 4, 200)
    shutil.copy2(a / "images" / "train" / "img0.jpg",
                 c / "images" / "train" / "img0.jpg")
    return [a, b, c]


def test_merge_detects_id_collisions(collections):
    plan = merge.plan(collections)
    ids = {row["id"]: set(row["names"]) for row in plan["conflicts"]["id_collisions"]}
    assert ids[0] == {"person", "forklift"}


def test_merge_detects_name_variants(collections):
    plan = merge.plan(collections)
    variants = [set(r["names"]) for r in plan["conflicts"]["name_variants"]]
    assert {"car", "Cars"} in variants
    assert plan["needs_a_decision"] is True


def test_merge_detects_cross_source_duplicates(collections):
    plan = merge.plan(collections)
    dupes = plan["conflicts"]["cross_source_duplicates"]
    assert len(dupes) == 1
    assert dupes[0]["identical"] is True
    assert {dupes[0]["a"]["source"], dupes[0]["b"]["source"]} == {0, 2}


def test_merge_preserves_class_meaning(collections, tmp_path):
    """The whole point: ids are rebuilt from names, so meaning survives."""
    plan = merge.plan(collections)
    out = tmp_path / "merged"
    merge.materialise(collections, plan, out)

    merged = Dataset(out)
    for src_i, src_root in enumerate(collections):
        src = Dataset(src_root)
        for s in src.samples:
            if not (s.label and s.label.boxes):
                continue
            meaning = src.names[s.label.boxes[0].cls]
            matches = [x for x in merged.samples
                       if x.stem.endswith(s.stem) and x.label and x.label.boxes
                       and merged.names[x.label.boxes[0].cls] == meaning]
            assert matches, f"source {src_i} {s.stem}: '{meaning}' was lost"


def test_merge_never_touches_the_sources(collections, tmp_path):
    before = {p: p.stat().st_mtime_ns
              for root in collections for p in root.rglob("*") if p.is_file()}
    plan = merge.plan(collections)
    merge.materialise(collections, plan, tmp_path / "merged")
    after = {p: p.stat().st_mtime_ns
             for root in collections for p in root.rglob("*") if p.is_file()}
    assert before == after


def test_merge_prefixes_colliding_filenames(collections, tmp_path):
    plan = merge.plan(collections)
    assert plan["conflicts"]["filename_collisions"]
    out = tmp_path / "merged"
    merge.materialise(collections, plan, out)
    merged = Dataset(out)
    # every source image survives; nothing was overwritten
    total = sum(sum(1 for s in Dataset(r).samples if s.image_path)
                for r in collections)
    assert sum(1 for s in merged.samples if s.image_path) == total


def test_merge_of_agreeing_datasets_has_no_conflicts(tmp_path):
    a = _collection(tmp_path / "a", ["person", "car"], 5, 0)
    b = _collection(tmp_path / "b", ["person", "car"], 5, 500)
    plan = merge.plan([a, b])
    c = plan["conflicts"]
    assert not c["id_collisions"] and not c["name_variants"]
    assert not c["cross_source_duplicates"]
    assert plan["needs_a_decision"] is False
    assert plan["merged_classes"] == ["car", "person"]


def test_name_normalisation():
    same = [("Fork_Lifts", "forklift"), ("car", "Cars"), ("hot dog", "hotdog")]
    for a, b in same:
        assert merge.normalise_name(a) == merge.normalise_name(b)
    assert merge.normalise_name("car") != merge.normalise_name("truck")
